fs.delete("/startup.lua")
fs.copy("disk/install_media/startup.lua", "/startup.lua")
fs.copy("disk/install_media/calls/", "/calls/")
disk.eject("top")
disk.eject("left")
disk.eject("right")
disk.eject("front")
disk.eject("back")
disk.eject("bottom")
os.reboot()