host = "http://localhost:8000"
term.setCursorPos(1,1)
term.write("Enter Account Name: ")
local name = read()
term.write("Enter Pin: ")
local pin = read("*")
local recv = http.get(host.."/account/"..name.."/money/get/", {pin=pin}).readAll()
term.clear()
term.setCursorPos(1,1)
term.write("Current Account Balance: "..recv)
term.setCursorPos(1,2)
term.write("Amount to Withdrawl: ")
local wit = read()
http.post(host.."/account/"..name.."/money/withdrawal/", string.format('{"pin":"%s","withdrawal":%d}', pin, tonumber(wit)), {["Content-Type"]="application/json"})
shell.run("startup")